<?php
/**
 * Plugin Name: DDG Corporate Content V2
 * Description: Production copy override for homepage and core company introduction pages.
 * Version: 2.0.0
 */
if (!defined('ABSPATH')) exit;

add_action('template_redirect', function () {
    if (is_admin() || is_feed() || wp_doing_ajax()) return;
    $path = trailingslashit((string) wp_parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH));
    $pages = ddg_corporate_v2_pages();
    if (!isset($pages[$path])) return;
    $d = $pages[$path];
    status_header(200);
    get_header();
    echo '<main class="ddgcf ddg-corporate-v2"><section class="ddgcf-hero"><div><p class="ey">'.esc_html($d['ey']).'</p><h1>'.esc_html($d['h1']).'</h1><p class="lead">'.esc_html($d['lead']).'</p></div></section><article><div class="ddgcf-in">'.wp_kses_post($d['html']).'</div></article></main>';
    get_footer();
    exit;
}, -200);

add_filter('pre_get_document_title', function($title){
    $path=trailingslashit((string)wp_parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH));
    $p=ddg_corporate_v2_pages(); return isset($p[$path])?$p[$path]['seo']:$title;
}, 200);

function ddg_corporate_v2_pages(){
 $cta=function($url,$label){return '<p><a href="'.esc_url(home_url($url)).'">'.esc_html($label).' →</a></p>';};
 return [
 '/'=>[
  'ey'=>'ĐĂNG DƯƠNG GROUP','h1'=>'Nâng tầm nhan sắc Việt','seo'=>'Đăng Dương Group | Mỹ phẩm, thương hiệu & hợp tác phát triển',
  'lead'=>'Đăng Dương Group phát triển hệ sinh thái mỹ phẩm kết nối sự thấu hiểu người dùng, phát triển sản phẩm, thương hiệu và các cơ hội hợp tác kinh doanh.',
  'html'=>'<h2>Phát triển mỹ phẩm từ sự thấu hiểu nhu cầu thực tế</h2><p>Đăng Dương Group hoạt động trong hệ sinh thái mỹ phẩm với trọng tâm là sản phẩm, thương hiệu, kiến thức chăm sóc và hợp tác. Với người tiêu dùng, chúng tôi hướng tới trải nghiệm dễ hiểu hơn để mỗi người nhận diện nhu cầu và lựa chọn sản phẩm phù hợp hơn với routine. Với đối tác, điểm bắt đầu là mục tiêu thực tế của dự án: sản phẩm dành cho ai, cần giải quyết nhu cầu nào và thương hiệu muốn phát triển theo hướng nào.</p>'.$cta('/ve-dang-duong/','Về Đăng Dương Group').'<h2>Năng lực phát triển</h2><p>Một sản phẩm mỹ phẩm cần bắt đầu từ việc làm rõ người dùng, nhu cầu chăm sóc và vai trò của sản phẩm. Từ nền tảng đó, dự án có thể đi tiếp qua nghiên cứu và phát triển, định hướng sản phẩm, sản xuất và mô hình hợp tác phù hợp với phạm vi đã thống nhất.</p><h3>Nghiên cứu & Phát triển</h3><p>Làm rõ nhu cầu, định hướng sản phẩm, nhóm người dùng và trải nghiệm mong muốn trước khi đi sâu vào giải pháp.</p>'.$cta('/nghien-cuu-phat-trien/','Tìm hiểu R&D').'<h3>OEM / ODM</h3><p>Đối tác có thể trao đổi nhu cầu phát triển sản phẩm hoặc thương hiệu theo mục tiêu và phạm vi dự án cụ thể.</p>'.$cta('/oem-odm-my-pham/','Tìm hiểu OEM / ODM').'<h2>Hệ sinh thái thương hiệu</h2><p>Các thương hiệu trong hệ sinh thái Đăng Dương được định hướng theo từng nhóm người dùng, nhu cầu chăm sóc và câu chuyện riêng. Website giúp người dùng đi từ nhu cầu tới thương hiệu và sản phẩm thay vì bắt đầu bằng một danh mục SKU rời rạc.</p>'.$cta('/thuong-hieu/','Khám phá thương hiệu').'<h2>Sản phẩm & Routine</h2><p>Đăng Dương định hướng trải nghiệm lựa chọn mỹ phẩm theo vai trò của từng bước chăm sóc. Người dùng có thể bắt đầu từ điều làn da đang cần, sau đó tìm hiểu routine và sản phẩm phù hợp với vai trò cần bổ sung.</p>'.$cta('/san-pham/','Khám phá sản phẩm & routine').'<h2>Hiểu trước khi lựa chọn</h2><p>Khu vực Kiến thức tập trung giải thích làn da, thành phần, routine và vai trò của sản phẩm theo cách dễ tiếp cận, giúp người dùng có thêm cơ sở trước khi lựa chọn và sử dụng mỹ phẩm.</p>'.$cta('/kien-thuc/','Khám phá kiến thức').'<h2>Cùng phát triển từ một nhu cầu cụ thể</h2><p>Đăng Dương Group kết nối các nhu cầu hợp tác từ đại lý, affiliate và phân phối đến trao đổi dự án OEM/ODM. Mỗi cuộc trao đổi bắt đầu bằng việc làm rõ mục tiêu, phạm vi và kỳ vọng của đối tác.</p>'.$cta('/doi-tac/','Tư vấn đại lý/Affiliate').$cta('/hop-tac-oem-odm/','Trao đổi dự án OEM/ODM')],
 '/ve-dang-duong/'=>[
  'ey'=>'VỀ ĐĂNG DƯƠNG','h1'=>'Kiến tạo giá trị trong ngành mỹ phẩm từ sự thấu hiểu','seo'=>'Về Đăng Dương Group | Hệ sinh thái mỹ phẩm & phát triển thương hiệu',
  'lead'=>'Đăng Dương Group phát triển hệ sinh thái mỹ phẩm với định hướng kết nối sản phẩm, thương hiệu, kiến thức chăm sóc và hợp tác kinh doanh.',
  'html'=>'<h2>Một hệ sinh thái được kết nối quanh ngành mỹ phẩm</h2><p>Đăng Dương Group không tiếp cận ngành mỹ phẩm từ một sản phẩm riêng lẻ. Hệ sinh thái được tổ chức quanh nhiều điểm chạm có liên quan: nghiên cứu và phát triển sản phẩm, thương hiệu, trải nghiệm người dùng, kiến thức chăm sóc, phân phối và hợp tác kinh doanh.</p><p>Sản phẩm cần phù hợp với nhu cầu người dùng. Thương hiệu cần có định hướng riêng. Nội dung cần giúp người đọc hiểu và lựa chọn tốt hơn. Hợp tác cần bắt đầu từ mục tiêu thực tế của hai bên.</p><h2>Nâng tầm nhan sắc Việt</h2><p>Đăng Dương hướng tới trải nghiệm chăm sóc bắt đầu từ việc hiểu bản thân, hiểu nhu cầu của làn da và lựa chọn những bước phù hợp hơn. Định hướng này được thể hiện qua ba nền tảng: hiểu người dùng, phát triển có mục tiêu và đồng hành lâu dài.</p><h3>Hiểu người dùng</h3><p>Bắt đầu từ nhu cầu và bối cảnh chăm sóc thực tế thay vì chỉ nhìn vào một danh mục sản phẩm.</p><h3>Phát triển có mục tiêu</h3><p>Mỗi sản phẩm hoặc dự án thương hiệu cần có vai trò, nhóm người dùng và mục tiêu rõ ràng.</p><h3>Đồng hành lâu dài</h3><p>Đăng Dương hướng tới mối quan hệ bền vững với người tiêu dùng, đại lý, đối tác nội dung và đối tác phát triển sản phẩm.</p><h2>Những lĩnh vực Đăng Dương kết nối</h2><p><strong>Nghiên cứu & phát triển:</strong> tìm hiểu nhu cầu, định hướng sản phẩm và các yếu tố liên quan trước khi bước vào quá trình phát triển cụ thể.</p><p><strong>Sản phẩm & thương hiệu:</strong> phát triển hệ sinh thái thương hiệu với từng nhóm sản phẩm và ngữ cảnh chăm sóc riêng.</p><p><strong>Kiến thức làm đẹp:</strong> giúp người dùng hiểu làn da, thành phần, routine và vai trò của sản phẩm rõ hơn.</p><p><strong>Phân phối & hợp tác:</strong> kết nối các nhu cầu về đại lý, affiliate, phân phối và phát triển sản phẩm hoặc thương hiệu.</p><h2>Bắt đầu từ câu hỏi đúng</h2><p>Một dự án mỹ phẩm có thể bắt đầu từ một ý tưởng sản phẩm, nhu cầu thị trường, thương hiệu mới hoặc kế hoạch mở rộng danh mục. Đăng Dương ưu tiên làm rõ đối tượng người dùng, nhu cầu, vai trò sản phẩm, mức độ hoàn thiện của ý tưởng và hình thức hợp tác trước khi xác định bước tiếp theo.</p>'.$cta('/cau-chuyen-dang-duong/','Đọc câu chuyện Đăng Dương').$cta('/doi-tac/','Trở thành đối tác')],
 '/cau-chuyen-dang-duong/'=>[
  'ey'=>'CÂU CHUYỆN ĐĂNG DƯƠNG','h1'=>'Từ sự thấu hiểu đến những giá trị có thể đồng hành lâu dài','seo'=>'Câu chuyện Đăng Dương Group | Từ sự thấu hiểu đến giá trị lâu dài',
  'lead'=>'Đăng Dương Group lựa chọn phát triển trong ngành mỹ phẩm bằng cách đặt nhu cầu thực tế của người dùng và mục tiêu của đối tác ở điểm bắt đầu của mỗi hành trình.',
  'html'=>'<h2>Mỹ phẩm không chỉ là một sản phẩm trên kệ</h2><p>Để thực sự có ý nghĩa với người dùng, một sản phẩm cần xuất hiện đúng nhu cầu và có vai trò rõ ràng trong trải nghiệm chăm sóc. Đó là góc nhìn Đăng Dương theo đuổi khi phát triển hệ sinh thái của mình.</p><p>Chúng tôi muốn người dùng bắt đầu bằng câu hỏi “mình đang cần chăm sóc điều gì?” trước khi hỏi “mua sản phẩm nào?”. Với đối tác cũng vậy: một dự án nên bắt đầu bằng việc hiểu doanh nghiệp đang muốn xây dựng điều gì và dành cho ai.</p><h2>Từ sản phẩm đến hệ sinh thái</h2><p>Khi một thương hiệu phát triển, sản phẩm liên quan đến cách thương hiệu được kể, cách người dùng được hướng dẫn, cách đại lý tư vấn, cách nội dung được truyền tải và cách đối tác tiếp tục phát triển danh mục. Vì vậy, Đăng Dương kết nối phát triển sản phẩm, thương hiệu, kiến thức chăm sóc, phân phối, đại lý, affiliate và hợp tác dự án trong cùng một hành trình.</p><h2>Từ bán sản phẩm đến giúp người dùng lựa chọn</h2><p>Đăng Dương định hướng nội dung và trải nghiệm để người dùng hiểu nhu cầu chăm sóc, vai trò của từng bước trong routine, khi nào một sản phẩm thực sự cần thiết và có thêm cơ sở để đưa ra lựa chọn phù hợp.</p><h2>Đồng hành từ mục tiêu, không chỉ từ một đơn hàng</h2><p>Với đối tác, Đăng Dương hướng tới việc trao đổi dựa trên bối cảnh cụ thể: sản phẩm dành cho ai, nhu cầu chính là gì, vai trò trong danh mục ra sao, thương hiệu muốn được nhớ đến như thế nào và bước phát triển tiếp theo cần đạt điều gì.</p><h2>Hành trình tiếp theo</h2><p>Đăng Dương Group tiếp tục hoàn thiện hệ sinh thái mỹ phẩm quanh ba nền tảng: hiểu người dùng, phát triển có mục tiêu và xây dựng quan hệ hợp tác lâu dài. Các dữ liệu lịch sử, pháp lý, quy mô và chứng nhận chỉ được công bố theo hồ sơ chính thức đã xác nhận.</p>'.$cta('/nang-luc/','Khám phá năng lực Đăng Dương').$cta('/lien-he/','Trao đổi cơ hội hợp tác')],
 '/tam-nhin-su-menh/'=>[
  'ey'=>'ĐỊNH HƯỚNG PHÁT TRIỂN','h1'=>'Tầm nhìn & Sứ mệnh','seo'=>'Tầm nhìn & Sứ mệnh | Đăng Dương Group',
  'lead'=>'Đăng Dương hướng tới một hệ sinh thái mỹ phẩm nơi sản phẩm, kiến thức và hợp tác cùng bắt đầu từ sự thấu hiểu nhu cầu thực tế.',
  'html'=>'<h2>Tầm nhìn</h2><p>Đăng Dương Group hướng tới phát triển một hệ sinh thái mỹ phẩm có khả năng kết nối người dùng, sản phẩm, thương hiệu và đối tác trong một hành trình rõ ràng hơn. Giá trị lâu dài không chỉ đến từ việc có thêm sản phẩm, mà từ khả năng giúp người dùng hiểu lựa chọn của mình và giúp đối tác xác định đúng hướng phát triển.</p><h2>Sứ mệnh</h2><p>Đăng Dương tập trung tạo ra những điểm chạm giúp nhu cầu được hiểu rõ hơn trước khi giải pháp được đề xuất: từ nội dung chăm sóc, trải nghiệm sản phẩm đến trao đổi phát triển thương hiệu và hợp tác kinh doanh.</p><h2>Định hướng thực thi</h2><p><strong>Với người dùng:</strong> cung cấp thông tin dễ hiểu để hỗ trợ lựa chọn và sử dụng mỹ phẩm có cơ sở hơn.</p><p><strong>Với thương hiệu:</strong> phát triển câu chuyện và danh mục theo nhóm nhu cầu, người dùng và vai trò sản phẩm.</p><p><strong>Với đối tác:</strong> bắt đầu bằng mục tiêu và phạm vi dự án để xác định hình thức hợp tác phù hợp.</p><p><strong>Với nội dung:</strong> ưu tiên thông tin có thể kiểm chứng; không biến các tuyên bố chưa xác minh thành cam kết công khai.</p>'.$cta('/gia-tri-thuong-hieu/','Khám phá giá trị Đăng Dương')],
 '/gia-tri-thuong-hieu/'=>[
  'ey'=>'GIÁ TRỊ ĐĂNG DƯƠNG','h1'=>'Những nguyên tắc định hướng cách Đăng Dương phát triển','seo'=>'Giá trị thương hiệu | Đăng Dương Group',
  'lead'=>'Sự thấu hiểu, tính rõ ràng, trách nhiệm với thông tin và tinh thần đồng hành là những nguyên tắc Đăng Dương đặt vào trải nghiệm người dùng và quan hệ đối tác.',
  'html'=>'<h2>Thấu hiểu trước khi đề xuất</h2><p>Chúng tôi ưu tiên làm rõ nhu cầu, bối cảnh và mục tiêu trước khi đi tới sản phẩm hoặc giải pháp. Điều này áp dụng cho cả trải nghiệm chăm sóc của người dùng và dự án của đối tác.</p><h2>Rõ ràng trong thông tin</h2><p>Nội dung cần giúp người đọc hiểu mình đang xem điều gì, sản phẩm có vai trò gì và bước tiếp theo là gì. Những dữ liệu cần xác minh như chứng nhận, công suất, tiêu chuẩn hay claim sản phẩm chỉ được công bố khi có nguồn phù hợp.</p><h2>Phát triển có mục tiêu</h2><p>Mỗi sản phẩm, thương hiệu và hoạt động hợp tác cần có đối tượng, vai trò và mục tiêu cụ thể thay vì phát triển chỉ để mở rộng số lượng.</p><h2>Đồng hành lâu dài</h2><p>Đăng Dương hướng tới quan hệ bền vững với người tiêu dùng và đối tác thông qua trải nghiệm nhất quán, trao đổi minh bạch và các bước phát triển phù hợp với nhu cầu thực tế.</p><h2>Học hỏi và hoàn thiện</h2><p>Ngành mỹ phẩm, hành vi người dùng và cách tiếp cận thị trường luôn thay đổi. Đăng Dương coi việc cập nhật kiến thức, kiểm tra dữ liệu và hoàn thiện trải nghiệm là một phần của quá trình phát triển.</p>'.$cta('/nang-luc/','Tìm hiểu năng lực').$cta('/doi-tac/','Hợp tác cùng Đăng Dương')]
 ];
}
