<?php
/**
 * Plugin Name: Bizrise DDG Content Final 2026
 * Description: Applies the approved DDG Content Master to website routes and verified product pages.
 * Version: 1.0.0
 */
if(!defined('ABSPATH'))exit;
final class DDG_Content_Final_2026{
 const V='1.0.0',OPT='ddg_content_final_2026_v';
 static array $seo=[];
 static array $r=[
 '/'=>['Đăng Dương Group','HOMEPAGE_CORPORATE_EXCELLENCE_P0.md',''],
 '/ve-dang-duong/'=>['Về Đăng Dương','BATCH_A_ABOUT_DDG_P0.md',''], '/cau-chuyen-dang-duong/'=>['Câu chuyện Đăng Dương','BATCH_A_ABOUT_DDG_P0.md',''], '/tam-nhin-su-menh/'=>['Tầm nhìn & Sứ mệnh','BATCH_A_ABOUT_DDG_P0.md',''], '/gia-tri-thuong-hieu/'=>['Giá trị thương hiệu','BATCH_A_ABOUT_DDG_P0.md',''], '/media-su-kien/'=>['Media & Sự kiện','BATCH_A_ABOUT_DDG_P0.md',''],
 '/nang-luc/'=>['Năng lực','CAPABILITY_CONTENT_MASTER_READY_QA.md',''], '/gia-cong-my-pham/'=>['Gia công mỹ phẩm','CAPABILITY_CONTENT_MASTER_READY_QA.md',''], '/oem-odm-my-pham/'=>['OEM / ODM mỹ phẩm','CAPABILITY_CONTENT_MASTER_READY_QA.md',''], '/nha-may-san-xuat-my-pham/'=>['Nhà máy sản xuất mỹ phẩm','CAPABILITY_CONTENT_MASTER_READY_QA.md',''], '/nghien-cuu-phat-trien/'=>['Nghiên cứu & Phát triển','CAPABILITY_CONTENT_MASTER_READY_QA.md',''], '/phat-trien-cong-thuc/'=>['Phát triển công thức','CAPABILITY_CONTENT_MASTER_READY_QA.md',''], '/quy-trinh-chat-luong/'=>['Quy trình chất lượng','CAPABILITY_CONTENT_MASTER_READY_QA.md',''], '/quy-trinh-gia-cong-my-pham/'=>['Quy trình gia công mỹ phẩm','CAPABILITY_CONTENT_MASTER_READY_QA.md',''],
 '/thuong-hieu/'=>['Thương hiệu','BATCH_C_BRAND_PRODUCT_ROUTINE_P0.md',''], '/thuong-hieu/one-today/'=>['One Today','BATCH_C_BRAND_PRODUCT_ROUTINE_P0.md','thuong-hieu'], '/thuong-hieu/hatagold/'=>['Hatagold','BATCH_C_BRAND_PRODUCT_ROUTINE_P0.md','thuong-hieu'], '/thuong-hieu/she-one/'=>['She One','BATCH_C_BRAND_PRODUCT_ROUTINE_P0.md','thuong-hieu'],
 '/san-pham/'=>['Sản phẩm','BATCH_C_BRAND_PRODUCT_ROUTINE_P0.md',''], '/san-pham/duong-sang-deu-mau/'=>['Dưỡng sáng & đều màu','BATCH_C_BRAND_PRODUCT_ROUTINE_P0.md','san-pham'], '/san-pham/cham-soc-da-mun/'=>['Chăm sóc da mụn','BATCH_C_BRAND_PRODUCT_ROUTINE_P0.md','san-pham'], '/san-pham/chong-nang/'=>['Chống nắng','BATCH_C_BRAND_PRODUCT_ROUTINE_P0.md','san-pham'], '/san-pham/dau-hieu-lao-hoa/'=>['Dấu hiệu lão hóa','BATCH_C_BRAND_PRODUCT_ROUTINE_P0.md','san-pham'], '/san-pham/cham-soc-body/'=>['Chăm sóc body','BATCH_C_BRAND_PRODUCT_ROUTINE_P0.md','san-pham'], '/routine-buoi-sang/'=>['Routine buổi sáng','BATCH_C_BRAND_PRODUCT_ROUTINE_P0.md',''], '/routine-buoi-toi/'=>['Routine buổi tối','BATCH_C_BRAND_PRODUCT_ROUTINE_P0.md',''], '/starter-routine/'=>['Starter Routine','BATCH_C_BRAND_PRODUCT_ROUTINE_P0.md',''], '/complete-routine/'=>['Complete Routine','BATCH_C_BRAND_PRODUCT_ROUTINE_P0.md',''],
 '/kien-thuc/'=>['Kiến thức','CONTENT_BATCH_D_KNOWLEDGE_PARTNER.md',''], '/hieu-lan-da/'=>['Hiểu làn da','CONTENT_BATCH_D_KNOWLEDGE_PARTNER.md',''], '/thanh-phan-my-pham/'=>['Thành phần mỹ phẩm','CONTENT_BATCH_D_KNOWLEDGE_PARTNER.md',''], '/routine-cach-dung/'=>['Routine & cách dùng','CONTENT_BATCH_D_KNOWLEDGE_PARTNER.md',''], '/cau-chuyen-san-pham/'=>['Câu chuyện sản phẩm','CONTENT_BATCH_D_KNOWLEDGE_PARTNER.md',''],
 '/doi-tac/'=>['Đối tác','CONTENT_BATCH_D_KNOWLEDGE_PARTNER.md',''], '/he-thong-phan-phoi/'=>['Hệ thống phân phối','CONTENT_BATCH_D_KNOWLEDGE_PARTNER.md',''], '/tim-diem-ban/'=>['Tìm điểm bán','CONTENT_BATCH_D_KNOWLEDGE_PARTNER.md',''], '/tro-thanh-dai-ly/'=>['Trở thành đại lý','CONTENT_BATCH_D_KNOWLEDGE_PARTNER.md',''], '/affiliate/'=>['Affiliate','CONTENT_BATCH_D_KNOWLEDGE_PARTNER.md',''], '/hop-tac-oem-odm/'=>['Hợp tác OEM/ODM','CONTENT_BATCH_D_KNOWLEDGE_PARTNER.md',''], '/lien-he/'=>['Liên hệ','CONTENT_BATCH_D_KNOWLEDGE_PARTNER.md','']];
 static function boot(){add_action('init',[__CLASS__,'pages'],120);add_action('template_redirect',[__CLASS__,'render'],-100);add_action('wp_enqueue_scripts',[__CLASS__,'css']);add_filter('pre_get_document_title',[__CLASS__,'title'],99);add_action('wp_head',[__CLASS__,'meta'],2);}
 static function pages(){if(get_option(self::OPT)===self::V)return;$ids=[];foreach(self::$r as $p=>$c){if($p==='/')continue;$s=self::slug($p);$o=get_page_by_path(trim($p,'/'),OBJECT,'page')?:get_page_by_path($s,OBJECT,'page');if($o)$ids[$s]=$o->ID;else{$id=wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_title'=>$c[0],'post_name'=>$s]);if(!is_wp_error($id))$ids[$s]=$id;}}foreach(self::$r as $p=>$c){if($p==='/'||empty($ids[self::slug($p)]))continue;$s=self::slug($p);$parent=$c[2]&&isset($ids[$c[2]])?$ids[$c[2]]:0;if((int)wp_get_post_parent_id($ids[$s])!==$parent)wp_update_post(['ID'=>$ids[$s],'post_parent'=>$parent]);}update_option(self::OPT,self::V,false);flush_rewrite_rules(false);}
 static function render(){if(is_admin()||is_feed()||wp_doing_ajax())return;$p=self::path();$redir=['/san-pham-routine/'=>'/san-pham/','/thuong-hieu/one-today-gold/'=>'/thuong-hieu/','/thuong-hieu/ever-today/'=>'/thuong-hieu/','/thuong-hieu/cream-x2/'=>'/thuong-hieu/'];if(isset($redir[$p])){wp_safe_redirect(home_url($redir[$p]),301);exit;}if(is_singular(['bizrise_product','ddg_product','product']))self::product();if(!isset(self::$r[$p]))return;$d=$p==='/'?self::home():self::data($p,self::$r[$p]);if(!$d)return;self::$seo=[$d['seo'],$d['meta']];status_header(200);get_header();echo'<main class="ddgcf"><section class="ddgcf-hero"><div><p class="ey">'.esc_html($d['ey']).'</p><h1>'.esc_html($d['h1']).'</h1><p class="lead">'.esc_html($d['lead']).'</p></div></section><article><div class="ddgcf-in">'.wp_kses_post($d['html']).'</div></article></main>';get_footer();exit;}
 static function data($p,$c){$m=self::source($c[1]);$s=self::section($m,$p);if(!$s)return[];$h=self::field($s,'H1')?:$c[0];$seo=self::field($s,'SEO Title')?:$h.' | Đăng Dương Group';$meta=self::field($s,'Meta Description')?:self::answer($s);$hero=self::sub($s,'Hero');$ey=self::field($hero,'Eyebrow')?:'ĐĂNG DƯƠNG GROUP';$lead=self::field($hero,'Support')?:self::answer($s);return['h1'=>$h,'seo'=>$seo,'meta'=>$meta,'ey'=>$ey,'lead'=>$lead,'html'=>self::md(self::public($s))];}
 static function home(){$h='Đăng Dương Group – Hệ sinh thái thương hiệu, sản phẩm và hợp tác mỹ phẩm';$lead='Website Đăng Dương Group được tổ chức như một điểm chạm corporate trước khi dẫn người xem tới thương hiệu và sản phẩm. Nội dung ưu tiên câu chuyện doanh nghiệp, năng lực có thể kiểm chứng, hệ thương hiệu, sản phẩm, routine, kiến thức và hợp tác.';$items=[['Đăng Dương Group là ai?','Tìm hiểu câu chuyện, định hướng và cách hệ sinh thái nội dung được tổ chức.','/ve-dang-duong/'],['Năng lực','Khám phá R&D, phát triển công thức, sản xuất, chất lượng và mô hình hợp tác theo dữ liệu có thể kiểm chứng.','/nang-luc/'],['OEM / ODM','Hiểu mô hình hợp tác theo trách nhiệm và đầu ra trước khi gửi brief dự án.','/oem-odm-my-pham/'],['Thương hiệu','Khám phá One Today, Hatagold và She One theo câu chuyện và nhóm sản phẩm đã xác minh.','/thuong-hieu/'],['Sản phẩm & Routine','Đi từ nhu cầu hoặc routine tới sản phẩm thay vì bắt đầu bằng một lưới SKU.','/san-pham/'],['Kiến thức','Hiểu làn da, thành phần, routine và vai trò sản phẩm trước khi lựa chọn.','/kien-thuc/'],['Đối tác','Chọn đúng luồng phân phối, đại lý, affiliate hoặc hợp tác OEM/ODM.','/doi-tac/']];$html='';foreach($items as $x)$html.='<h2>'.esc_html($x[0]).'</h2><p>'.esc_html($x[1]).'</p><p><a href="'.esc_url(home_url($x[2])).'">Khám phá</a></p>';return['h1'=>$h,'seo'=>'Đăng Dương Group | Thương hiệu, sản phẩm & hợp tác mỹ phẩm','meta'=>$lead,'ey'=>'ĐĂNG DƯƠNG GROUP','lead'=>$lead,'html'=>$html];}
 static function product(){$id=get_queried_object_id();if(get_post_meta($id,'_bizrise_ddg_content_gate',true)!=='PUBLISH_ALLOWED')return;$n=get_the_title($id);$b=self::pm($id,['brand_name','brand','product_brand'])?:'Đăng Dương';$g=self::pm($id,['product_group','_product_group'])?:'mỹ phẩm';$z=self::pm($id,['_bizrise_ddg_pack','product_pack']);self::$seo=[$n.' | '.$b,'Thông tin '.$n.' của '.$b.': nhóm '.$g.', vị trí gợi ý trong routine và dữ liệu sản phẩm theo hồ sơ đã xác minh.'];status_header(200);get_header();echo'<main class="ddgcf"><section class="ddgcf-hero"><div><p class="ey">'.esc_html($b).'</p><h1>'.esc_html($n).'</h1><p class="lead">'.esc_html(self::pintro($n,$b,$g,$z)).'</p></div></section><article><div class="ddgcf-in">';if(has_post_thumbnail($id))echo get_the_post_thumbnail($id,'large',['class'=>'prodimg','loading'=>'eager']);echo'<h2>Thông tin đã xác minh</h2><p><strong>Thương hiệu:</strong> '.esc_html($b).'</p><p><strong>Nhóm sản phẩm:</strong> '.esc_html($g).'</p>'.($z?'<p><strong>Quy cách:</strong> '.esc_html($z).'</p>':'').'<h2>Vai trò trong routine</h2><p>'.esc_html(self::role($g)).'</p><h2>Cách sử dụng</h2><p>Sử dụng theo hướng dẫn trên nhãn hoặc bao bì hiện hành của sản phẩm.</p><h2>Lưu ý</h2><p>Ngưng sử dụng nếu xuất hiện phản ứng không phù hợp và tham khảo chuyên gia y tế khi cần. Thông tin cảnh báo chi tiết theo nhãn hiện hành.</p><h2>Tiếp tục hành trình</h2><p><a href="'.esc_url(home_url('/starter-routine/')).'">Xem routine</a> · <a href="'.esc_url(home_url('/tim-diem-ban/')).'">Tìm điểm bán</a></p></div></article></main>';get_footer();exit;}
 static function source($f){$a=WPMU_PLUGIN_DIR.'/data/ddg-content/'.$f;if(!is_readable($a)&&defined('ABSPATH')){$root=dirname(rtrim(ABSPATH,'/'));$b=$root.'/repositories/myphamdangduong/docs/content/'.$f;if(is_readable($b))$a=$b;}return is_readable($a)?(string)file_get_contents($a):'';}
 static function section($m,$p){$l=explode("\n",str_replace("\r",'',$m));$st=-1;$lv=0;foreach($l as $i=>$x)if(preg_match('/^(#{1,4})\s+/', $x,$q)&&str_contains($x,'`'.$p.'`')){$st=$i;$lv=strlen($q[1]);break;}if($st<0)return'';$o=[];for($i=$st+1;$i<count($l);$i++){if(preg_match('/^(#{1,4})\s+/', $l[$i],$q)&&strlen($q[1])<=$lv)break;$o[]=$l[$i];}return trim(join("\n",$o));}
 static function field($s,$k){$q=preg_quote($k,'/');return preg_match('/(?:^|\n)\s*(?:[-*]\s*)?\*\*'.$q.':\*\*\s*(.+)$/miu',$s,$m)?trim($m[1]):'';}
 static function answer($s){$x=self::sub($s,'Direct Answer');foreach(preg_split('/\n\s*\n/u',$x) as $p){$p=trim(preg_replace('/^#+.*$/mu','',$p));if($p!=='')return wp_strip_all_tags($p);}return'';}
 static function sub($s,$name){$l=explode("\n",$s);$st=-1;$lv=0;foreach($l as $i=>$x)if(preg_match('/^(#{1,5})\s+(.+)$/u',$x,$m)&&stripos(preg_replace('/[*`]/u','',$m[2]),$name)!==false){$st=$i;$lv=strlen($m[1]);break;}if($st<0)return'';$o=[];for($i=$st+1;$i<count($l);$i++){if(preg_match('/^(#{1,5})\s+/', $l[$i],$m)&&strlen($m[1])<=$lv)break;$o[]=$l[$i];}return trim(join("\n",$o));}
 static function public($s){$l=explode("\n",$s);$o=[];$skip=0;foreach($l as $x){if(preg_match('/^(#{1,5})\s+(.+)$/u',$x,$m)){$lv=strlen($m[1]);$t=preg_replace('/[*`]/u','',$m[2]);if($skip&&$lv<=$skip)$skip=0;if(preg_match('/SEO brief|Fact Source|Fact status|Internal links|Business confirmation gate|Hero$/iu',$t)){$skip=$lv;continue;}if(preg_match('/Direct Answer|CTA$/iu',$t))continue;}if($skip||str_contains($x,'[TBD'))continue;if(preg_match('/^\s*\*\*(Eyebrow|Headline|Support|Primary Keyword|Intent|SEO Title|Meta Description|H1|CTA chính|CTA phụ):\*\*/iu',$x))continue;if(trim($x)==='---')continue;$o[]=$x;}return trim(join("\n",$o));}
 static function md($s){$h='';$p=[];$ul=false;$flush=function()use(&$h,&$p){if($p){$h.='<p>'.self::in(join(' ',$p)).'</p>';$p=[];}};foreach(explode("\n",$s) as $x){$t=trim($x);if($t===''){if($ul){$h.='</ul>';$ul=false;}$flush();continue;}if(preg_match('/^(#{2,5})\s+(.+)$/u',$t,$m)){if($ul){$h.='</ul>';$ul=false;}$flush();$n=min(4,max(2,strlen($m[1])));$h.='<h'.$n.'>'.self::in($m[2]).'</h'.$n.'>';continue;}if(preg_match('/^[-*]\s+(.+)$/u',$t,$m)){if(!$ul){$flush();$h.='<ul>';$ul=true;}$h.='<li>'.self::in($m[1]).'</li>';continue;}if(preg_match('/^\d+\.\s+(.+)$/u',$t,$m)){if($ul){$h.='</ul>';$ul=false;}$flush();$h.='<p>'.self::in($m[1]).'</p>';continue;}$p[]=$t;}if($ul)$h.='</ul>';$flush();return$h;}
 static function in($s){$s=esc_html($s);$s=preg_replace('/\*\*(.+?)\*\*/u','<strong>$1</strong>',$s);return preg_replace_callback('/`(\/[^`]+)`/u',fn($m)=>'<a href="'.esc_url(home_url($m[1])).'">'.esc_html($m[1]).'</a>',$s);}
 static function path(){if(is_front_page())return'/';$p=(string)wp_parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH);return'/'.trim($p,'/').'/';}
 static function slug($p){$a=array_values(array_filter(explode('/',trim($p,'/'))));return(string)end($a);}
 static function pm($id,$ks){foreach($ks as $k){$v=trim((string)get_post_meta($id,$k,true));if($v!=='')return$v;}return'';}
 static function pintro($n,$b,$g,$z){return$n.' là sản phẩm thuộc nhóm '.$g.' của '.$b.($z?', quy cách '.$z:'').'. Tên, thương hiệu, nhóm và quy cách được dùng theo hồ sơ xác minh; lợi ích chi tiết chỉ trình bày theo dữ liệu claim được duyệt.';}
 static function role($g){$x=mb_strtolower($g);if(str_contains($x,'chống nắng'))return'Bước bảo vệ ban ngày, theo hướng dẫn riêng của sản phẩm.';if(str_contains($x,'sữa rửa mặt')||str_contains($x,'body wash'))return'Bước làm sạch trước các sản phẩm chăm sóc khác.';if(str_contains($x,'serum'))return'Sau làm sạch và trước bước kem/dưỡng nếu routine có nhiều bước.';if(str_contains($x,'body')||str_contains($x,'tắm'))return'Trong routine chăm sóc cơ thể, theo hướng dẫn trên nhãn.';return'Bước chăm sóc/dưỡng sau làm sạch; thời điểm sử dụng theo hướng dẫn của SKU.';}
 static function css(){if(!isset(self::$r[self::path()])&&!is_singular(['bizrise_product','ddg_product','product']))return;wp_register_style('ddgcf',false,[],self::V);wp_enqueue_style('ddgcf');wp_add_inline_style('ddgcf',':root{--r:#9c1232;--i:#241f22;--iv:#fbf7f2}.ddgcf{font-family:"Be Vietnam Pro",sans-serif;color:var(--i)}.ddgcf-hero{background:linear-gradient(135deg,#fff7f5,var(--iv));padding:76px 20px}.ddgcf-hero>div,.ddgcf-in{max-width:920px;margin:auto}.ey{font-size:12px;letter-spacing:.18em;color:var(--r);font-weight:700}.ddgcf h1{font-size:clamp(36px,5vw,68px);line-height:1.08;margin:14px 0}.lead{font-size:19px;line-height:1.75;color:#574c51}.ddgcf article{padding:58px 20px 90px}.ddgcf h2{font-size:32px;margin:48px 0 16px}.ddgcf h3{font-size:21px;margin:30px 0 10px}.ddgcf p,.ddgcf li{font-size:16px;line-height:1.85;color:#4c4247}.ddgcf a{color:var(--r);font-weight:650}.prodimg{max-width:560px;width:100%;height:auto;border-radius:22px;margin:0 0 32px}@media(max-width:700px){.ddgcf-hero{padding:52px 14px}.ddgcf article{padding:38px 14px 70px}.ddgcf h2{font-size:27px}}');}
 static function title($t){return self::$seo[0]??$t;}static function meta(){if(!empty(self::$seo[1]))echo'<meta name="description" content="'.esc_attr(self::$seo[1]).'">\n';}
}
DDG_Content_Final_2026::boot();
