<?php
if (!defined('ABSPATH')) { exit; }

final class Bizrise_DDG_Homepage_V12 {
    private const V='1.2.0';
    private const HERO='https://dangduonggroup.com/wp-content/uploads/2026/08/hatagold-b5-banner-16x9-1.jpg';
    private const FACTORY1='https://dangduonggroup.com/wp-content/uploads/2026/08/1785897611517_8276717302965400709_8276717302965400709_1b1840f22b403366d34c51b66b09b35b.jpg';
    private const FACTORY2='https://dangduonggroup.com/wp-content/uploads/2026/08/1785897624946_8276717302965400709_8276717302965400709_cd933faca283531c50fcda70e36b7a00.jpg';
    private const CORPORATE='https://dangduonggroup.com/wp-content/uploads/2026/08/232323my-pham-dang-duong-1.jpg';

    public static function boot():void{
        add_action('wp_enqueue_scripts',[__CLASS__,'assets'],1200);
        add_action('template_redirect',[__CLASS__,'route'],-100);
    }
    private static function home():bool{return trim((string)parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH),'/')==='';}
    public static function assets():void{
        if(is_admin()||!self::home())return;
        wp_dequeue_style('ddg-homepage-v1');wp_dequeue_script('ddg-homepage-v1');
        wp_enqueue_style('ddg-homepage-v12',plugin_dir_url(__FILE__).'assets/home-v12.css',[],self::V);
        wp_enqueue_script('ddg-homepage-v12',plugin_dir_url(__FILE__).'assets/home-v12.js',[],self::V,true);
    }
    public static function route():void{
        if(is_admin()||wp_doing_ajax()||is_feed()||is_embed()||!self::home())return;
        self::render();exit;
    }
    private static function logo(string $extra=''):void{
        $id=(int)get_theme_mod('custom_logo');
        if($id>0){$img=wp_get_attachment_image($id,'full',false,['class'=>'ddgh-logo-img','alt'=>'Đăng Dương Group','loading'=>'eager','decoding'=>'async']);if($img){echo '<a class="ddgh-logo '.$extra.'" href="'.esc_url(home_url('/')).'">'.$img.'</a>';return;}}
        echo '<a class="ddgh-logo ddgh-logo-text '.$extra.'" href="'.esc_url(home_url('/')).'">Đăng Dương Group</a>';
    }
    private static function img_id(int $id):int{
        foreach(['_ddg_pc_image_id','_thumbnail_id'] as $k){$m=(int)get_post_meta($id,$k,true);if($m>0&&wp_attachment_is_image($m))return $m;}
        $m=(int)get_post_thumbnail_id($id);if($m>0&&wp_attachment_is_image($m))return $m;
        $key=trim((string)get_post_meta($id,'_bizrise_ddg_master_key',true));if($key==='')return 0;
        global $wpdb;$legacy=(int)$wpdb->get_var($wpdb->prepare("SELECT p.ID FROM {$wpdb->posts} p INNER JOIN {$wpdb->postmeta} pm ON pm.post_id=p.ID WHERE p.post_type IN ('bizrise_product','ddg_product') AND pm.meta_key=%s AND pm.meta_value=%s ORDER BY p.ID ASC LIMIT 1",'_bizrise_ddg_master_key',$key));
        if($legacy<1)return 0;foreach(['_ddg_pc_image_id','_thumbnail_id'] as $k){$m=(int)get_post_meta($legacy,$k,true);if($m>0&&wp_attachment_is_image($m))return $m;}$m=(int)get_post_thumbnail_id($legacy);return $m>0&&wp_attachment_is_image($m)?$m:0;
    }
    private static function allowed(int $id):bool{return strtoupper(trim((string)get_post_meta($id,'_bizrise_ddg_content_gate',true)))==='PUBLISH_ALLOWED'&&in_array(strtolower(trim((string)get_post_meta($id,'_bizrise_ddg_regulatory_status',true))),['','active'],true);}
    private static function products(int $limit=6):array{
        $ids=get_posts(['post_type'=>'product','post_status'=>'publish','posts_per_page'=>40,'fields'=>'ids','orderby'=>'menu_order date','order'=>'DESC']);$out=[];
        foreach($ids as $id){$id=(int)$id;if(!self::allowed($id))continue;$img=self::img_id($id);if($img<1)continue;$out[]=['id'=>$id,'img'=>$img];if(count($out)>=$limit)break;}return $out;
    }
    private static function meta(int $id,array $keys):string{foreach($keys as $k){$v=trim((string)get_post_meta($id,$k,true));if($v!=='')return $v;}return '';}
    private static function value(string $n,string $t,string $c):void{echo '<article><span>'.$n.'</span><div><strong>'.esc_html($t).'</strong><small>'.esc_html($c).'</small></div></article>';}
    private static function brand(string $name,string $copy,string $url):void{echo '<article class="ddgh-brand-card"><a href="'.esc_url($url).'"><div class="ddgh-brand-mark">'.esc_html($name).'</div><div><h3>'.esc_html($name).'</h3><p>'.esc_html($copy).'</p><span>Khám phá landing →</span></div></a></article>';}
    private static function render_products():void{
        $items=self::products(6);echo '<section class="ddgh-section ddgh-products"><div class="ddgh-shell"><header class="ddgh-heading"><p class="ddgh-kicker">SẢN PHẨM</p><h2>Khám phá danh mục trong hệ sinh thái Đăng Dương</h2><p>Sản phẩm được tổ chức theo thương hiệu và nhu cầu để người dùng tìm hiểu nhanh hơn.</p></header>';
        if($items){echo '<div class="ddgh-product-rail">';foreach($items as $it){$id=$it['id'];$brand=self::meta($id,['brand_name','_ddg_brand','product_brand']);$pack=self::meta($id,['_bizrise_ddg_pack','product_pack','_ddg_pack_size']);$img=wp_get_attachment_image($it['img'],'medium_large',false,['loading'=>'lazy','decoding'=>'async','alt'=>get_the_title($id).($brand?' - '.$brand:'')]);echo '<article class="ddgh-product-card"><a href="'.esc_url(get_permalink($id)).'"><div class="ddgh-product-media">'.$img.'</div><div class="ddgh-product-body"><p>'.esc_html($brand?:'Đăng Dương Group').'</p><h3>'.esc_html(get_the_title($id)).'</h3>'.($pack?'<span>'.esc_html($pack).'</span>':'').'</div></a></article>';}echo '</div>';}else{echo '<article class="ddgh-products-editorial"><img src="'.esc_url(self::CORPORATE).'" width="1600" height="900" alt="Sản phẩm Đăng Dương Group" loading="lazy" decoding="async"><div><h3>Khám phá danh mục sản phẩm</h3><p>Xem sản phẩm theo thương hiệu và nhu cầu tại trang sản phẩm.</p><a class="ddgh-btn" href="'.esc_url(home_url('/san-pham/')).'">Xem danh mục</a></div></article>';}
        echo '</div></section>';
    }
    private static function news():void{
        $posts=get_posts(['post_type'=>'post','post_status'=>'publish','numberposts'=>3,'orderby'=>'date','order'=>'DESC']);echo '<div class="ddgh-news-grid">';
        foreach($posts as $p){$img=(int)get_post_thumbnail_id($p->ID);echo '<article class="ddgh-news-card"><a href="'.esc_url(get_permalink($p)).'">';if($img)echo '<div class="ddgh-news-media">'.wp_get_attachment_image($img,'medium_large',false,['loading'=>'lazy','decoding'=>'async','alt'=>get_the_title($p)]).'</div>';echo '<div class="ddgh-news-body"><small>'.esc_html(get_the_date('d.m.Y',$p)).'</small><h3>'.esc_html(get_the_title($p)).'</h3><p>'.esc_html(wp_trim_words(get_the_excerpt($p),20)).'</p><strong>Đọc tiếp →</strong></div></a></article>';}
        if(!$posts)echo '<article class="ddgh-news-empty"><h3>Kiến thức đang được cập nhật</h3></article>';echo '</div>';
    }
    private static function render():void{
        status_header(200);nocache_headers();$mobile=(int)get_option('ddg_home_hero_mobile_id',0);$mobile_url=$mobile?(string)wp_get_attachment_image_url($mobile,'full'):self::HERO;
?><!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Đăng Dương Group | Kiến tạo giá trị cho thương hiệu mỹ phẩm Việt</title><meta name="description" content="Đăng Dương Group kết nối phát triển sản phẩm, hệ sinh thái thương hiệu và giải pháp hợp tác B2B cho ngành mỹ phẩm Việt."><link rel="canonical" href="<?php echo esc_url(home_url('/')); ?>"><?php wp_head(); ?></head><body <?php body_class('ddgh-homepage ddgh-home-b2b'); ?>><?php wp_body_open(); ?>
<header class="ddgh-header"><div class="ddgh-topbar"><div class="ddgh-shell"><span>Đăng Dương Group — Kiến tạo giá trị cho thương hiệu mỹ phẩm Việt</span><nav><a href="<?php echo esc_url(home_url('/tuyen-dung/')); ?>">Tuyển dụng</a><a href="<?php echo esc_url(home_url('/kien-thuc/')); ?>">Tin tức</a><a href="<?php echo esc_url(home_url('/lien-he/')); ?>">Liên hệ</a></nav></div></div><div class="ddgh-nav-wrap"><div class="ddgh-shell ddgh-nav-row"><?php self::logo(); ?><button class="ddgh-menu-toggle" type="button" aria-expanded="false" aria-controls="ddgh-primary" aria-label="Mở menu">☰</button><nav id="ddgh-primary" class="ddgh-primary"><a class="is-active" href="<?php echo esc_url(home_url('/')); ?>">Trang chủ</a><a href="<?php echo esc_url(home_url('/ve-dang-duong-group/')); ?>">Giới thiệu</a><a href="<?php echo esc_url(home_url('/nang-luc/')); ?>">Năng lực</a><a href="<?php echo esc_url(home_url('/oem-odm/')); ?>">OEM/ODM</a><a href="<?php echo esc_url(home_url('/thuong-hieu/')); ?>">Thương hiệu</a><a href="<?php echo esc_url(home_url('/san-pham/')); ?>">Sản phẩm</a><a href="<?php echo esc_url(home_url('/kien-thuc/')); ?>">Kiến thức</a><a href="<?php echo esc_url(home_url('/lien-he/')); ?>">Liên hệ</a></nav><a class="ddgh-header-cta" href="<?php echo esc_url(home_url('/lien-he/')); ?>">Trao đổi nhu cầu</a></div></div></header>
<main id="main-content">
<section class="ddgh-hero"><picture class="ddgh-hero-media" aria-hidden="true"><source media="(max-width:767px)" srcset="<?php echo esc_url($mobile_url); ?>"><img src="<?php echo esc_url(self::HERO); ?>" width="1920" height="1080" alt="" fetchpriority="high" decoding="async"></picture><div class="ddgh-hero-scrim"></div><div class="ddgh-shell ddgh-hero-content"><div class="ddgh-hero-copy"><p class="ddgh-kicker">ĐĂNG DƯƠNG GROUP</p><h1>Kiến tạo giá trị cho thương hiệu mỹ phẩm Việt</h1><p class="ddgh-answer">Đăng Dương Group kết nối phát triển sản phẩm, hệ sinh thái thương hiệu và các giải pháp hợp tác B2B trong một trải nghiệm thống nhất, rõ ràng và dễ mở rộng.</p><div class="ddgh-actions"><a class="ddgh-btn" href="<?php echo esc_url(home_url('/nang-luc/')); ?>">Khám phá năng lực</a><a class="ddgh-btn ddgh-btn--ghost" href="<?php echo esc_url(home_url('/lien-he/')); ?>">Liên hệ tư vấn</a></div></div></div></section>
<section class="ddgh-value-strip"><div class="ddgh-shell ddgh-value-grid"><?php self::value('01','Nghiên cứu & phát triển','Từ nhu cầu đến hướng phát triển sản phẩm.');self::value('02','Sản xuất & kiểm soát','Tổ chức quy trình và điểm kiểm soát theo hồ sơ.');self::value('03','OEM/ODM','Đồng hành theo phạm vi của từng dự án.');self::value('04','Phát triển thương hiệu','Kết nối sản phẩm, media và trải nghiệm số.'); ?></div></section>
<section class="ddgh-section ddgh-profile"><div class="ddgh-shell ddgh-profile-grid"><div class="ddgh-factory-collage"><figure class="ddgh-factory-main"><img src="<?php echo esc_url(self::FACTORY1); ?>" width="1600" height="1000" alt="Không gian Đăng Dương Group" loading="lazy" decoding="async"></figure><figure><img src="<?php echo esc_url(self::FACTORY2); ?>" width="1200" height="800" alt="Hoạt động tại Đăng Dương Group" loading="lazy" decoding="async"></figure><figure><img src="<?php echo esc_url(self::CORPORATE); ?>" width="1200" height="800" alt="Hệ sinh thái mỹ phẩm Đăng Dương Group" loading="lazy" decoding="async"></figure></div><div class="ddgh-profile-copy"><p class="ddgh-kicker">HỒ SƠ DOANH NGHIỆP</p><h2>Một nền tảng B2B để thương hiệu đi từ ý tưởng đến thị trường rõ ràng hơn</h2><p>Đăng Dương Group tổ chức năng lực phát triển sản phẩm, thương hiệu và nội dung theo một cấu trúc thống nhất để đối tác dễ nhìn thấy phạm vi hợp tác và bước tiếp theo.</p><div class="ddgh-profile-points"><article><strong>Phát triển sản phẩm</strong><span>Từ brief đến hướng phát triển và dữ liệu cần quản lý.</span></article><article><strong>Thương hiệu & thị trường</strong><span>Kết nối sản phẩm với định vị, media và trải nghiệm số.</span></article><article><strong>Hợp tác dài hạn</strong><span>Một đầu mối chung cho các nhu cầu B2B.</span></article></div><div class="ddgh-actions"><a class="ddgh-btn" href="<?php echo esc_url(home_url('/ve-dang-duong-group/')); ?>">Xem hồ sơ doanh nghiệp</a><a class="ddgh-text-link" href="<?php echo esc_url(home_url('/nang-luc/')); ?>">Khám phá năng lực →</a></div></div></div></section>
<section class="ddgh-section ddgh-solutions"><div class="ddgh-shell"><header class="ddgh-heading ddgh-heading--left"><p class="ddgh-kicker">GIẢI PHÁP CHO ĐỐI TÁC</p><h2>Chọn điểm bắt đầu phù hợp với nhu cầu của thương hiệu</h2></header><div class="ddgh-solution-grid"><article><span>01</span><h3>OEM/ODM</h3><p>Từ brief, hướng phát triển, mẫu đến các bước triển khai theo phạm vi dự án.</p><a href="<?php echo esc_url(home_url('/oem-odm/')); ?>">Tìm hiểu OEM/ODM →</a></article><article><span>02</span><h3>Phát triển thương hiệu</h3><p>Kết nối định vị, sản phẩm, media và nội dung thành trải nghiệm nhất quán.</p><a href="<?php echo esc_url(home_url('/thuong-hieu/')); ?>">Khám phá thương hiệu →</a></article><article><span>03</span><h3>Sản phẩm & phân phối</h3><p>Khám phá danh mục theo thương hiệu và nhu cầu sử dụng.</p><a href="<?php echo esc_url(home_url('/san-pham/')); ?>">Xem sản phẩm →</a></article></div></div></section>
<section class="ddgh-section ddgh-process"><div class="ddgh-shell"><header class="ddgh-heading"><p class="ddgh-kicker">QUY TRÌNH HỢP TÁC</p><h2>Từ nhu cầu đến một lộ trình có thể theo dõi</h2></header><ol class="ddgh-process-list"><li><span>01</span><strong>Tiếp nhận nhu cầu</strong><small>Xác định mục tiêu và phạm vi.</small></li><li><span>02</span><strong>Phân tích & đề xuất</strong><small>Chuyển brief thành hướng triển khai.</small></li><li><span>03</span><strong>Phát triển</strong><small>Sản phẩm, thương hiệu hoặc nội dung.</small></li><li><span>04</span><strong>Kiểm tra & hoàn thiện</strong><small>Đối chiếu dữ liệu và trải nghiệm.</small></li><li><span>05</span><strong>Bàn giao & đồng hành</strong><small>Kết nối bước tiếp theo.</small></li></ol></div></section>
<section class="ddgh-section ddgh-brands"><div class="ddgh-shell"><header class="ddgh-heading"><p class="ddgh-kicker">HỆ SINH THÁI THƯƠNG HIỆU</p><h2>Mỗi thương hiệu là một trải nghiệm riêng trong cùng network</h2></header><div class="ddgh-brand-grid"><?php self::brand('One Today','Chăm sóc mỗi ngày, rõ ràng theo routine.','https://one-today.dangduonggroup.com/');self::brand('She One','Không gian làm đẹp nữ tính và hiện đại.','https://she-one.dangduonggroup.com/');self::brand('Cream X2','Nhận diện riêng, thông tin sản phẩm rõ ràng.','https://x2.dangduonggroup.com/');self::brand('Hatagold','Ngôn ngữ premium ấm áp và chỉn chu.','https://hatagold.dangduonggroup.com/');self::brand('Ever Today','Tinh thần tươi mới, nhẹ nhàng và gần gũi.','https://ever-today.dangduonggroup.com/');self::brand('One Today Gold','Trải nghiệm premium trong hệ One Today.','https://one-today-gold.dangduonggroup.com/'); ?></div></div></section>
<?php self::render_products(); ?>
<section class="ddgh-showcase"><picture class="ddgh-showcase-media" aria-hidden="true"><img src="<?php echo esc_url(self::CORPORATE); ?>" width="1920" height="1080" alt="" loading="lazy" decoding="async"></picture><div class="ddgh-showcase-scrim"></div><div class="ddgh-shell ddgh-showcase-content"><p class="ddgh-kicker">ĐỒNG HÀNH CÙNG THƯƠNG HIỆU</p><h2>Một hệ sinh thái — nhiều điểm bắt đầu cho hợp tác</h2><p>Từ hồ sơ doanh nghiệp, năng lực, OEM/ODM, thương hiệu đến sản phẩm, mọi điểm chạm đều dẫn về một đầu mối tư vấn chung.</p><a class="ddgh-btn ddgh-btn--light" href="<?php echo esc_url(home_url('/lien-he/')); ?>">Gửi yêu cầu tư vấn</a></div></section>
<section class="ddgh-section ddgh-news"><div class="ddgh-shell"><header class="ddgh-heading ddgh-heading--left"><p class="ddgh-kicker">KIẾN THỨC & THỊ TRƯỜNG</p><h2>Nội dung hỗ trợ quyết định tốt hơn</h2></header><?php self::news(); ?></div></section>
<section class="ddgh-network-cta"><div class="ddgh-shell ddgh-network-cta-grid"><div><p class="ddgh-kicker">ĐĂNG DƯƠNG GROUP</p><h2>Sẵn sàng trao đổi về sản phẩm, thương hiệu hoặc OEM/ODM?</h2><p>Một đầu mối chung cho toàn bộ network.</p></div><a class="ddgh-btn ddgh-btn--light" href="<?php echo esc_url(home_url('/lien-he/')); ?>">Liên hệ tư vấn</a></div></section>
</main>
<footer class="ddgh-footer"><div class="ddgh-shell ddgh-footer-grid"><div><?php self::logo('ddgh-logo--footer'); ?><p>Kiến tạo giá trị cho thương hiệu mỹ phẩm Việt thông qua sản phẩm, thương hiệu và trải nghiệm số nhất quán.</p></div><div><h3>Về Đăng Dương</h3><a href="<?php echo esc_url(home_url('/ve-dang-duong-group/')); ?>">Giới thiệu</a><a href="<?php echo esc_url(home_url('/nang-luc/')); ?>">Năng lực</a><a href="<?php echo esc_url(home_url('/oem-odm/')); ?>">OEM/ODM</a></div><div><h3>Hệ sinh thái</h3><a href="<?php echo esc_url(home_url('/thuong-hieu/')); ?>">Thương hiệu</a><a href="<?php echo esc_url(home_url('/san-pham/')); ?>">Sản phẩm</a><a href="<?php echo esc_url(home_url('/kien-thuc/')); ?>">Kiến thức</a></div><div><h3>Liên hệ</h3><a href="<?php echo esc_url(home_url('/lien-he/')); ?>">Gửi yêu cầu tư vấn</a></div></div><div class="ddgh-shell ddgh-copyright">© <?php echo esc_html(wp_date('Y')); ?> Đăng Dương Group.</div></footer>
<?php wp_footer(); ?></body></html><?php }
}
Bizrise_DDG_Homepage_V12::boot();
